# Dependencies
markdown:         kramdown
highlighter:      rouge
excerpt_separator: "<!--more-->"

# Plugins
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            NLPer
tagline:          'Natural Language Processing and Machine Learning'
description:      'Natural Language Processing and Machine Learning. Excited in learning new things. Made by <a href="https://twitter.com/raphaelshu" target="_blank">@raphaelshu</a>.'
url:              http://nlper.com
baseurl:          /

author:
  name:           'Raphael Shu'
  url:            https://twitter.com/raphaelshu 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zomux
