# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            NLPer
tagline:          'Natural Language Processing and Machine Learning'
description:      'Natural Language Processing and Machine Learning. Made by <a href="https://twitter.com/raphaelshu" target="_blank">@raphaelshu</a>.'
url:              http://nlper.com
baseurl:          /

author:
  name:           'Raphael Shu'
  url:            https://twitter.com/raphaelshu 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zomux
