# Dependencies
markdown:         kramdown
highlighter:      rouge
excerpt_separator: "<!--more-->"

# Plugins
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            NLPer
tagline:          'Building Internet-Scale Intelligence through Natural Language'
description:      'Natural Language Processing, AI Agents, Multi-Agent Collaboration and Internet-Scale Group Intelligence. Excited in learning new things. Made by <a href="https://twitter.com/raphaelshu" target="_blank">@raphaelshu</a>.'
url:              http://nlper.com
baseurl:          /

author:
  name:           'Raphael Shu'
  url:            https://twitter.com/raphaelshu 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zomux
